### ISSUE TITLE
Pushing local IP

### ISSUE THREAD

**Issue by dentralp** [willswire/unifi-cloudflare-ddns#17] opened 2022-08-09 22:18 UTC
Probably user error, but this is pushing the local IP rather than external IP to cloudflare for me

![dns](https://user-images.githubusercontent.com/110943358/183771692-ec8dda40-ae6c-4c46-b7ae-7bdf51df7e87.png)
?

**Comment by willswire** [comment] 2022-08-12 02:08
Duplicate of #18

**Closed by willswire** 2022-08-12 02:08 UTC

**Comment by zhudhjen** [comment] 2024-08-29 16:06
@dentrolp were you able to resolve this? I encountered the same issue and the link above did not help me.

**Comment by zhudhjen** [comment] 2024-08-29 16:08
NVM I found #36 being the actual problem on my side.
